Repository ucfopen/UDOIT, pull requests merged in 2024-04, with the labels that each got.

#937 Updated primary contact on README
  README.md
Labels: documentation

#900 Allow UDOIT to accept modern filetypes
  assets/js/Components/FilesModal.js
  assets/js/Components/FilesPage.js
  src/Lms/Canvas/CanvasApi.php
  src/Lms/Canvas/CanvasLms.php
  src/Lms/D2l/D2lLms.php
  src/Lms/LmsInterface.php
  src/Services/LmsPostService.php
  translations/en.json
  translations/es.json
Labels: bug, javascript, php

#947 Updated dependencies in composer.lock
  composer.lock
Labels: dependencies

#946 Cleanup console printouts
  assets/js/Components/Admin/UsersPage.js
  assets/js/Components/App.js
  assets/js/Components/Forms/HeadingEmptyForm.js
  assets/js/Components/Forms/TableHeaders.js
  assets/js/Services/Html.js
  assets/js/getInitialData.js
Labels: cleanup
